version: '3.1'

services:
  app:
    build: .
    container_name: to-do-list-application
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://127.0.0.1:5433/codekitchen
      - SPRING_DATASOURCE_USERNAME=codekitchen
      - SPRING_DATASOURCE_PASSWORD=123
    depends_on:
      - db

  db:
    image: postgres:15.3
    container_name: db_postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=codekitchen
      - POSTGRES_USER=codekitchen
      - POSTGRES_PASSWORD=123